require("impatient") -- keep at top
require("n8.options")
require("n8.keymaps")
require("n8.plugins")
require("n8.colorscheme")
require("n8.cmp")
require("n8.lsp")
require("n8.telescope")
require("n8.treesitter")
require("n8.autopairs")
require("n8.comments")
require("n8.gitsigns")
require("n8.lualine")
require("n8.bufferline")
require("n8.neo-tree")
require("n8.neogit")
